#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

###### extensions ######

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# Now we can pipe to multiple outputs!
setopt MULTIOS

# This makes cd=pushd
setopt AUTO_PUSHD

# This will use named dirs when possible
setopt NO_AUTO_NAME_DIRS

# Keep echo "station" > station from clobbering station
setopt CLOBBER

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# see $ man zshoptions
setopt EXTENDED_GLOB

##### Customize to your needs... ####

if [[ -s "$HOME/.aliases" ]]; then
  . "$HOME/.aliases"
fi

if [[ -s "$HOME/.osxrc" ]]; then
  . "$HOME/.osxrc"
fi

if [[ -s "$HOME/.linuxrc" ]]; then
  . "$HOME/.linuxrc"
fi

if [[ -s "$HOME/.secrets" ]]; then
  . "$HOME/.secrets"
fi
