#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export TERM="xterm-256color"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#export SUBLIME=subl
#export EDITOR="$SUBLIME --wait"
#export VISUAL=$EDITOR
export LSCOLORS="exfxcxdxbxegedabagacad"

###### extensions ######

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# Now we can pipe to multiple outputs!
setopt MULTIOS

# This makes cd=pushd
setopt AUTO_PUSHD

# This will use named dirs when possible
setopt NO_AUTO_NAME_DIRS

# Keep echo "station" > station from clobbering station
setopt CLOBBER

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# see $ man zshoptions
setopt EXTENDED_GLOB

# Push and pop directories on directory stack
alias pu='pushd'
alias po='popd'

# Basic directory operations
alias ...='cd ../..'
alias -- -='cd -'

# Super user
alias _='sudo'
alias please='sudo'

# List direcory contents
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'
alias sl=ls # often screw this up

# better cd
alias ..='cd ..'
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias cd.....='cd ../../../..'
alias cd/='cd /'


# directory operations shortcuts
alias md='mkdir -p'
alias rd=rmdir
alias d='dirs -v | head -10'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/edder/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/edder/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/edder/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/edder/google-cloud-sdk/completion.zsh.inc'; fi


##### Customize to your needs... ####

if [[ -s "$HOME/.aliases" ]]; then
  . "$HOME/.aliases"
fi

if [[ -s "$HOME/.osxrc" ]]; then
  . "$HOME/.osxrc"
fi

if [[ -s "$HOME/.vagrantrc" ]]; then
  . "$HOME/.vagrantrc"
fi

